
## -----------------------------------------------------------------------------
## IMPORTANT: In accordance with YunoHost's spirit, please keep things simple and 
## do not overwhelm the admin with tons of misunderstandable or advanced settings.
## -----------------------------------------------------------------------------

version = "1.0"


[main]
name.en = "Main configuration"
name.fr = "Configuration principale"
services = ["__APP__", "__APP___workers"]

     
    [main.config]
    name.en = "Configuration options"
    name.fr = "Options de configuration"

