#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dawarich"
name = "Dawarich"
description.en = "Self-hostable alternative to Google Timeline "

version = "0.30.6~ynh1"

maintainers = ["Thovi98"]

[upstream]

license = "AGPL-3.0"
website = "https://dawarich.app/"
admindoc = "https://dawarich.app/docs/intro"
code = "https://github.com/Freika/dawarich"

fund = "https://www.patreon.com/freika"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dawarich"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Freika/dawarich/archive/refs/tags/0.30.6.tar.gz"
    sha256 = "7d33153b588a7454483015d46c31cf9cbc87e93263daa527e957c6fc9f12eb2d"
    
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    
    [resources.apt]
packages = [
    # Ruby
    "build-essential", "gcc", "g++", "autoconf", "bison", "make",
    "libssl-dev", "libyaml-dev", "libreadline6-dev", "zlib1g-dev",
    "libncurses5-dev", "libffi-dev", "libgdbm-dev", "libgdbm6",
    "libjemalloc-dev", "pkg-config",

    # gems Ruby
    "libxml2-dev", "libxslt1-dev",    
    "libpq-dev",                      
    "libicu-dev",                    
    "libidn11-dev",                  
    "protobuf-compiler", "libprotobuf-dev", 

    # Posqgresql & db
    "postgresql", "postgresql-contrib", "postgresql-postgis",
    "redis-server", "redis-tools",
]

    [resources.database]
    type = "postgresql"
