#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "example"
name = "Example app"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "0.30.6~ynh1"

maintainers = ["Thovi98"]

[upstream]

license = "AGPL-3.0"
website = "https://dawarich.app/"
admindoc = "https://dawarich.app/docs/intro"
code = "https://github.com/Freika/dawarich"

fund = "https://www.patreon.com/freika"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dawarich"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Freika/dawarich/archive/refs/tags/0.30.6.tar.gz"
    sha256 = "7d33153b588a7454483015d46c31cf9cbc87e93263daa527e957c6fc9f12eb2d"
    
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, postgresql-postgis, build-essential, pkg-config, libpq-dev, libffi-dev, libyaml-dev, zlib1g-dev, redis-server"

    [resources.database]
    type = "postgresql"
