#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

#ynh_config_remove_fail2ban

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi
if ynh_hide_warnings yunohost service status ${app}-sidekiq >/dev/null; then
	yunohost service remove ${app}-sidekiq
fi

ynh_config_remove_systemd "${app}"
ynh_config_remove_systemd "${app}-sidekiq"

ynh_config_remove_nginx

ynh_redis_remove_db "$redis_db"

# Remove metapackage and its dependencies
ynh_ruby_remove
ynh_nodejs_remove

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
