#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

### (Same as for install dir)
chown -R "$app:$app" "$data_dir"

#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling Ruby and NodeJS..."

ruby_version=$(cat $install_dir/.ruby-version)
ynh_ruby_install

ynh_nodejs_install

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell  < "./db.sql"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
ynh_restore "/etc/systemd/system/$app-sidekiq.service"
systemctl enable "$app-sidekiq.service" --quiet

ynh_config_add_systemd --service="${app}" --template="dawarich.service"
ynh_config_add_systemd --service="${app}-sidekiq" --template="dawarich-sidekiq.service"

yunohost service add "$app" --description="$app’s service" --log="/var/log/$app/$app.log"
yunohost service add "$app-sidekiq" --description="$app sidekiq service" --log="/var/log/$app/$app-sidekiq.log"

ynh_restore "/etc/logrotate.d/$app"

#ynh_restore "/etc/fail2ban/jail.d/$app.conf"
#ynh_restore "/etc/fail2ban/filter.d/$app.conf"
#ynh_systemctl --action=restart --service=fail2ban

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --log_path=/var/log/$app/$app.log --wait_until="Listening on"
ynh_systemctl --service=${app}-sidekiq --action="start" --log_path=/var/log/$app/$app-sidekiq.log --wait_until="Firing startup event"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
